---
# tasks file for dnsmasq
- name: Install packages
  apt:
     name: "{{ packages }}"
     state: present
     update_cache: yes
  vars:
      packages:
      - dnsmasq
      - policykit-1
  notify: 
  - dnsmasq handler

- name: configure dnsmasq 
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "{{ item.regexp }}" 
    line: "{{ item.line }}"
    state: present
    backup: yes 
  loop:
     - { regexp: '#port=5353', line: 'port=5353' }
     - { regexp: '#interface=', line: 'interface=eth0' }