---
# tasks file for fluentd
- name: install fluentd
  shell: curl -fsSL https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent4.sh | sh
  ignore_errors: True
  
- name: copy configfile
  copy: 
     src: td-agent.conf
     dest: /etc/td-agent/td-agent.conf

- name: stop fluentd service
  service: 
     name: td-agent
     state: stopped

- name: pause 1 sec because faced this error - td-agent.service Start request repeated too quickly.
  pause:
     seconds: 5   

- name: start fluentd service
  service: 
     name: td-agent
     state: started     